name: barryisett
favicon: null
layout_spectrum: 0.61008
typography_spectrum: 0.8743446674197912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#fdfdfd'
    - '#c0c4c7'
    - '#7a7a7a'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5390638085082173
purpose: []
